return {
  'MeanderingProgrammer/render-markdown.nvim',
  ft = { 'markdown' },
  opts = {
    render_modes = { 'n', 'no', 'c', 't', 'i', 'ic' },
    anti_conceal = {
      ignore = {
        head_background = true,
        head_border = true,
        head_icon = true,
      },
    },
    checkbox = {
      enable = true,
      position = 'inline',
    },
    code = {
      sign = false,
      border = 'thin',
      position = 'right',
      width = 'block',
      above = '▁',
      below = '▔',
      language_left = '█',
      language_right = '█',
      language_border = '▁',
      left_pad = 1,
      right_pad = 1,
    },
    heading = {
      width = 'block',
      backgrounds = {
        'RenderMarkdownH1Bg',
        'RenderMarkdownH2Bg',
        'RenderMarkdownH3Bg',
        'RenderMarkdownH4Bg',
        'RenderMarkdownH5Bg',
        'RenderMarkdownH6Bg',
      },
      foregrounds = {
        'RenderMarkdownH1',
        'RenderMarkdownH2',
        'RenderMarkdownH3',
        'RenderMarkdownH4',
        'RenderMarkdownH5',
        'RenderMarkdownH6',
      },
      sign = false,
      left_pad = 1,
      right_pad = 0,
      position = 'right',
      icons = {
        '',
        '',
        '',
        '',
        '',
        '',
      },
      -- icons = {
      --   " ",
      --   " ",
      --   " ",
      --   " ",
      --   " ",
      --   " ",
      -- },
      -- icons = {
      --   "█ ",
      --   "██ ",
      --   "███ ",
      --   "████ ",
      --   "█████ ",
      --   "██████ ",
      -- },
    },
  },
}
